---
- name: Configure bash defaults.
  copy: 
    src: dotfiles/skel/
    dest: /etc/skel/

- name: Add bash and vim configuration for user profile.
  copy: 
    src: dotfiles/skel/
    dest: "/home/{{ ansible_user }}/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    # Never replace files if they already exist.
    force: False

- name: Add root bashrc and vim configuration. (Debian)
  copy: 
    src: "{{ item }}"
    dest: /root/
    owner: root
    group: root
  with_list:
    - dotfiles/root/.bashrc
  when: ansible_os_family == 'Debian'

- name: Add root bashrc and vim configuration. (RedHat)
  lineinfile:
    path: /root/.bashrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^(export )?EDITOR='
      line: 'export EDITOR=vim.basic'
    - regexp: '^(export )?VISUAL='
      line: 'export VISUAL=vim.basic'
    - regexp: '^(export )?HISTCONTROL='
      line: 'HISTCONTROL=ignoreboth'
  when: ansible_os_family == 'RedHat'

- name: Add bash and vim configuration for root profile.
  copy: 
    src: dotfiles/skel/
    dest: /root/
    owner: root
    group: root
    # Never replace files if they already exist.
    force: False
